---
title: "data_exploration"
author: "Alina Kereszt"
date: "2024-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
pacman::p_load(tidyverse, 
               ggplot2)
```

```{r load data}
df <- read.csv("data/data.csv")
```

```{r select cols}
df <- df %>% 
  select(c(ID, 
           FaceID, 
           FirstRating, 
           GroupRating, 
           SecondRating,
           Feedback,
           Change))
```

```{r nas}
rows_with_na <- df[!complete.cases(df), ]
rows_with_na
# oopsie! wherever there is NA in Feedback, GroupRating is 0 - NOT on the 
# accepted scale (1-8)
```

```{r no of participants}
num_unique_ids <- df %>% 
  select(ID) %>% 
  distinct() %>% 
  n_distinct()
num_unique_ids
```

```{r no of faces}
num_unique_fids <- df %>% 
  select(FaceID) %>% 
  distinct() %>% 
  n_distinct()
num_unique_fids
```

```{r first ratings}
plot_first_ratings <- ggplot(df, aes(x = factor(FirstRating))) +
  geom_bar(fill = 'steelblue') +
  labs(title = "Distribution of initial ratings",
       x = "First rating",
       y = "Count") +
  theme_minimal()
```

```{r group ratings}
plot_group_ratings <- ggplot(df, aes(x = factor(GroupRating))) +
  geom_bar(fill = 'steelblue') +
  labs(title = "Distribution of group ratings",
       x = "Group rating",
       y = "Count") +
  theme_minimal()
```

```{r second ratings}
plot_second_ratings <- ggplot(df, aes(x = factor(SecondRating))) +
  geom_bar(fill = 'steelblue') +
  labs(title = "Distribution of ratings after receiving feedback",
       x = "Second rating",
       y = "Count") +
  theme_minimal()
```

```{r feedback}
plot_feedback <- ggplot(df, aes(x = factor(Feedback))) +
  geom_bar(fill = 'steelblue') +
  labs(title = "Distribution of feedback",
       x = "Feedback from group rating",
       y = "Count") +
  theme_minimal()
```

```{r change}
plot_change <- ggplot(df, aes(x = factor(Change))) +
  geom_bar(fill = 'steelblue') +
  labs(title = "Distribution of rating changes",
       x = "Change in rating after receiving group feedback",
       y = "Count") +
  theme_minimal()
```

```{r save plots}
ggsave("plots/plot_first_ratings.png", 
       plot_first_ratings, 
       width = 4, 
       height = 3)
ggsave("plots/plot_group_ratings.png", 
       plot_group_ratings, 
       width = 4, 
       height = 3)
ggsave("plots/plot_second_ratings.png", 
       plot_second_ratings, 
       width = 4, 
       height = 3)
ggsave("plots/plot_feedback.png", 
       plot_feedback, 
       width = 4, 
       height = 3)
ggsave("plots/plot_change.png", 
       plot_change, 
       width = 4, 
       height = 3)
```

















