---
title: "simple_bayes_modelling"
author: "Martine Lind Jensen"
date: "2024-04-12"
output: html_document
---
```{r}
pacman::p_load(cmdstanr, tidyverse, brms)

set.seed(1234)
```


```{r}
#Create function to simulate data 

sim_simple_f <- function(bias, FirstRating, GroupRating) {
  
  #Check if this is actually what we are modelling??
  outcome <- inv_logit_scaled(bias + 0.5*logit_scaled(FirstRating/9) + 0.5*logit_scaled(GroupRating/9))
  
  return(outcome)
}

#Simulate some data 

bias <- seq(0,1,0.1)
trials <- seq(10)
FirstRating <- seq(1,8, 1)
GroupRating <- seq(1,8, 1)

sim_data_simB <- expand.grid(bias = bias, trials = trials, FirstRating = FirstRating, GroupRating = GroupRating)

for (n in seq(nrow(sim_data_simB))) {
  sim_data_simB$belief[n] <- sim_simple_f(sim_data_simB$bias[n], sim_data_simB$FirstRating[n], sim_data_simB$GroupRating[n])
  sim_data_simB$choice[n] <- round(sim_data_simB$belief[n]*9, 0) #need to make a choice, should we sample or just take the straight value? And then we need to figure out how we are gonna make it 1-8 again
}
```

```{r compiling model}
file <- file.path("simple_sc.stan")

model_simple <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
```

```{r fitting model on simulated data}

d_sim_simple_bias0.7 <- sim_data_simB %>% filter(bias == "0.7")


d_sim_simple <- list(
  N = nrow(d_sim_simple_bias0.7), 
  SecondRating = d_sim_simple_bias0.7$choice, 
  FirstRating = d_sim_simple_bias0.7$FirstRating, 
  GroupRating = d_sim_simple_bias0.7$GroupRating
)

samples_simple_sc_sim <- model_simple$sample(
  data = d_sim_simple, 
  #fixed_param = TRUE,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)

samples_simple_sc_sim$save_object("models/simple_sc_sim.rds")
```

```{r}
samples_simple_sc_sim <- readRDS("models/simple_sc_sim.rds")

samples_simple_sc_sim$cmdstan_diagnose() 

samples_simple_sc_sim$summary()

samples_simple_sc_sim$loo()
```

```{r}
draws_sim_sim <- as_draws_df(samples_simple_sc_sim$draws())
```

Chains seem fine
```{r}
ggplot(draws_sim_sim, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_sim, aes(.iteration, bias_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_sim, aes(.iteration, st_d, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

```

```{r}
sim_sim_bias <- ggplot(draws_sim_sim) +
  geom_density(aes(bias), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = d_sim_simple_bias0.7$bias[1]) +
  theme_bw() 
sim_sim_bias

sim_sim_sd <- ggplot(draws_sim_sim) +
  geom_density(aes(st_d), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(sd_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = sim_data_weightB$bias[1]) +
  theme_bw() + 
  xlim(-1,1)

```

```{r fitting model to real data}
#remove na's in data 

df <- read_csv("data/data.csv")

df <- na.omit(df)

#subsetting to one participant
subset1 <- df %>% subset(Participant ==86)

data <- list(
  N = nrow(subset1), 
  SecondRating = subset1$SecondRating, 
  FirstRating = subset1$FirstRating, 
  GroupRating = subset1$GroupRating
)

samples_simple_sc <- model_simple$sample(
  data = data,
  #fixed_param = TRUE,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)

samples_simple_sc$save_object("models/simple_sc.rds")
```

```{r}
samples_simple_sc <- readRDS("models/simple_sc.rds")

samples_simple_sc$cmdstan_diagnose() #function checking the chains and stuff

samples_simple_sc$summary() # summarize the model

samples_simple_sc$loo()
```

```{r}
# Extract posterior samples and include sampling of the prior:
draws_simple <- as_draws_df(samples_simple_sc$draws())
```

Model checking and plotting
```{r}
ggplot(draws_sim_sim, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_sim, aes(.iteration, bias_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_sim, aes(.iteration, st_d, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_sim, aes(.iteration, sd_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
```

```{r}
simple_bias <- ggplot(draws_sim_sim) +
  geom_density(aes(bias), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = sim_data_weightB$bias[1]) +
  theme_bw() + 
  xlim(-1,1)

simple_bias

```

```{r looping through each participant}
#creating a list for a for loop to go through, modelling by each participant
participant_list <- unique(df$Participant)

draws_simple <- c()

loos_simple <- c()

for (i in participant_list){ 
  
  data_subject <- filter(df, Participant == i)
  
  data <- list(
    N = nrow(data_subject), 
    SecondRating = data_subject$SecondRating, 
    FirstRating = data_subject$FirstRating, 
    GroupRating = data_subject$GroupRating
  )
  
  samples_simple <- model_simple$sample(
    data = data,
    #fixed_param = TRUE,
    seed = 123,
    chains = 2,
    parallel_chains = 2,
    threads_per_chain = 2,
    iter_warmup = 1500,
    iter_sampling = 3000,
    refresh = 500
  )
  #loo <- samples_simple$loo()
  
  #loos_simple[i] <- loo
  
  #adding the draws to the dataframe
  temp_df <- as_draws_df(samples_simple$draws())
  
  temp_df <- temp_df %>% 
    mutate(subject = i)
  
  if (exists("draws_simple")) {draws_simple <- rbind(draws_simple, temp_df)} #remember to clean if reusing
  else{draws_simple <- temp_df}
  
  
  }
```

```{r chains by participants}
ggplot(draws_simple, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic() + 
  facet_wrap(.~subject)

ggplot(draws_simple, aes(.iteration, bias_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic() + 
  facet_wrap(.~subject)

ggplot(draws_simple, aes(.iteration, st_d, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()+ 
  facet_wrap(.~subject)

ggplot(draws_simple, aes(.iteration, sd_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()+ 
  facet_wrap(.~subject)

```

```{r by individual participants}
ggplot(draws_simple) +
  geom_density(aes(bias), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = sim_data_weightB$bias[1]) +
  theme_bw() + 
  facet_wrap(.~subject)
```