---
title: "weighted_bayes_modelling"
author: "Martine Lind Jensen"
date: "2024-04-23"
output: html_document
---
```{r}
pacman::p_load(cmdstanr, tidyverse, brms)

set.seed(1234)
```

```{r}
#Create function to simulate data 

sim_weighted_f <- function(bias, FirstRating, GroupRating, weight1, weight2) {
  
  weight1 <- (weight1 - 0.5)*2
  weight2 <- (weight2 - 0.5)*2
  
  #Check if this is actually what we are modelling??
  outcome <- inv_logit_scaled(bias + weight1*logit_scaled(FirstRating/9) + weight2*logit_scaled(GroupRating/9))
  
  return(outcome)
}

#Simulate some data 

bias <- 0
trials <- seq(1)
FirstRating <- seq(1,8, 1)
GroupRating <- seq(1,8, 1)
weight1 <- seq(0.5, 1, 0.1)
weight2 <- seq(0.5, 1, 0.1)

sim_data_weightB <- expand.grid(bias = bias, trials = trials, FirstRating = FirstRating, GroupRating = GroupRating, weight1 = weight1, weight2 = weight2)

for (n in seq(nrow(sim_data_weightB))) {
  sim_data_weightB$belief[n] <- sim_weighted_f(sim_data_weightB$bias[n], sim_data_weightB$FirstRating[n], sim_data_weightB$GroupRating[n], sim_data_weightB$weight1[n], sim_data_weightB$weight2[n])
  sim_data_weightB$choice[n] <- round(sim_data_weightB$belief[n]*9, 0) 
  
  if (sim_data_weightB$choice[n] == 0) {sim_data_weightB$choice[n] <- 1}
  
  if (sim_data_weightB$choice[n] == 9) {sim_data_weightB$choice[n] <- 8}
}

```


```{r compiling model}
file <- file.path("weighted_bayes_sc.stan")

model_weighted <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))
```

```{r fitting model on simulated data}
sim_data_weightB1 <-  sim_data_weightB %>% subset(weight1 == 0.7 & weight2 == 0.9) 

df_sim_weight <- list(
  N = nrow(sim_data_weightB1), 
  SecondRating = sim_data_weightB1$choice, 
  FirstRating = sim_data_weightB1$FirstRating, 
  GroupRating = sim_data_weightB1$GroupRating
)

samples_weighted_sc_sim <- model_weighted$sample(
  data = df_sim_weight,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500, 
  max_treedepth = 20,
  adapt_delta = 0.99,
)

samples_weighted_sc_sim$save_object("models/weighted_sc_sim.rds")
```

```{r}
samples_weighted_sc_sim <- readRDS("models/weighted_sc_sim.rds")

samples_weighted_sc_sim$cmdstan_diagnose() #function checking the chains and stuff

samples_weighted_sc_sim$summary() # summarize the model

samples_weighted_sc_sim$loo()
```

```{r}
draws_sim_weighted <- as_draws_df(samples_weighted_sc_sim$draws())
```

```{r}
ggplot(draws_sim_weighted, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_weighted, aes(.iteration, bias_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_weighted, aes(.iteration, st_d, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_weighted, aes(.iteration, weight1, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_sim_weighted, aes(.iteration, weight2, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

```

```{r}
sim_weight_bias <- ggplot(draws_sim_weighted) +
  geom_density(aes(bias), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = sim_data_weightB1$bias[1]) +
  theme_bw()
sim_weight_bias
sim_weight_w1 <- ggplot(draws_sim_weighted) +
  geom_density(aes(weight1), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(w1_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = sim_data_weightB1$weight1[1]) +
  theme_bw()
sim_weight_w1
sim_weight_w2 <- ggplot(draws_sim_weighted) +
  geom_density(aes(weight2), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(w2_prior), alpha = 0.6, fill = "pink") +
  geom_vline(xintercept = sim_data_weightB1$weight2[1]) +
  theme_bw()
sim_weight_w2
```


```{r cleaning data}
#remove na's in data 

df <- read_csv("data/data.csv")

df <- na.omit(df)
```



```{r fitting model to real data 1 participant }
subset1 <- df %>% subset(Participant == 86)


data <- list(
  N = nrow(subset1), 
  SecondRating = subset1$SecondRating, 
  FirstRating = subset1$FirstRating, 
  GroupRating = subset1$GroupRating
)

samples_weighted_sc <- model_weighted$sample(
  data = data,
  #fixed_param = TRUE,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1500,
  iter_sampling = 3000,
  refresh = 500
)

samples_weighted_sc$save_object("models/weighted_sc.rds")
```

```{r}
samples_weighted_sc <- readRDS("models/weighted_sc.rds")

samples_weighted_sc$cmdstan_diagnose() #function checking the chains and stuff

samples_weighted_sc$summary()

samples_weighted_sc$loo()
```

```{r}
draws_weighted <- as_draws_df(samples_weighted_sc$draws())
```

```{r means}
weighted_bias <- ggplot(draws_weighted) +
  geom_density(aes(bias), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = sim_data_weightB$bias[1]) +
  theme_bw() 

weighted_bias
weighted_w1 <- ggplot(draws_weighted) +
  geom_density(aes(weight1), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(w1_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = sim_data_weightB$weight1[1]) +
  theme_bw()


weighted_w1
weighted_w2 <- ggplot(draws_weighted) +
  geom_density(aes(weight2), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(w2_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = db1$w2[1]) +
  theme_bw()
```

```{r chain }
ggplot(draws_weighted, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_weighted, aes(.iteration, bias_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()
ggplot(draws_weighted, aes(.iteration, st_d, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_weighted, aes(.iteration, sd_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()


ggplot(draws_weighted, aes(.iteration, weight1, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

ggplot(draws_weighted, aes(.iteration, weight2, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()

```

```{r looping through each participant}
#creating a list for a for loop to go through, modelling by each participant
participant_list <- unique(df$Participant)

for (i in participant_list){ 
  
  data_subject <- filter(df, Participant == i)
  
  data <- list(
    N = nrow(data_subject), 
    SecondRating = data_subject$SecondRating, 
    FirstRating = data_subject$FirstRating, 
    GroupRating = data_subject$GroupRating
  )
  
  samples_weighted <- model_weighted$sample(
    data = data,
    #fixed_param = TRUE,
    seed = 123,
    chains = 2,
    parallel_chains = 2,
    threads_per_chain = 2,
    iter_warmup = 1500,
    iter_sampling = 3000,
    refresh = 500
  )
  
  #adding the draws to the dataframe
  temp_df <- as_draws_df(samples_weighted$draws())
  
  temp_df <- temp_df %>% 
    mutate(subject = i)
  
  if (exists("draws_weighted")) {draws_weighted <- rbind(draws_weighted, temp_df)} #remember to clean if reusing
  else{draws_weighted <- temp_df}
  
  
  }
```

```{r chains by participants}
ggplot(draws_weighted, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic() + 
  facet_wrap(.~subject)

ggplot(draws_weighted, aes(.iteration, bias_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic() + 
  facet_wrap(.~subject)

ggplot(draws_weighted, aes(.iteration, st_d, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()+ 
  facet_wrap(.~subject)

ggplot(draws_weighted, aes(.iteration, sd_prior, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()+ 
  facet_wrap(.~subject)

ggplot(draws_weighted, aes(.iteration, weight1, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()+ 
  facet_wrap(.~subject)

ggplot(draws_weighted, aes(.iteration, weight2, group = .chain, color = .chain)) +
  geom_line(alpha = 0.5) +
  theme_classic()+ 
  facet_wrap(.~subject)

```

```{r by individual participants}
ggplot(draws_weighted) +
  geom_density(aes(bias), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(bias_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = sim_data_weightB$bias[1]) +
  theme_bw() + 
  facet_wrap(.~subject)

ggplot(draws_weighted) +
  geom_density(aes(weight1), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(w1_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = sim_data_weightB$weight1[1]) +
  theme_bw()+ 
  facet_wrap(.~subject)

ggplot(draws_weighted) +
  geom_density(aes(weight2), alpha = 0.6, fill = "darkolivegreen4") +
  geom_density(aes(w2_prior), alpha = 0.6, fill = "pink") +
  #geom_vline(xintercept = db1$w2[1]) +
  theme_bw()+ 
  facet_wrap(.~subject) + 
  ylim(0,50)
```


```{r}
#Model comparison
loo_simple <- samples_simple_sc$loo()
loo_weighted <- samples_weighted_sc$loo()
comparison <- loo_compare(loo_simple, loo_weighted)

```

